server:
  port: 8100
spring:
  profiles:
    active: local

---

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: my_first_group
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  config:
    activate:
      on-profile: local

---

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeSerializer
      group-id: my_first_group
  config:
    activate:
      on-profile: dev

---

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeSerializer
      group-id: my_first_group
  config:
    activate:
      on-profile: prod